name: unit-test
on: [push]
  tests:
    runs-on: ubuntu-latest
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: dev

      - name: unit-test
        run: make tests_run > test_tests.txt

      - name: coverage
        run: make coverage > test_coverage.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Upload
          path: ./test_*.txt