name: unit-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: dev

      - name: unit-test
        run: make tests_run

      - name: coverage
        run: make coverage