name: unit-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2.3.4
      repository: ${{ github.repository }}
      ref: 'dev'
      - name: unit-test
        run: make test_run
      - name: coverage
        run: make coverage