name: unit-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: dev

      - name: maker
        run: make

      - name: check-bin
        id: check_bin
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: "do-op"

      - name: unit-test
        run: make tests_run

      - name: coverage
        run: make coverage > test_coverage.txt

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: "test_coverage.txt"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Upload
          path: ./test_*.txt
          retention-days: 5
          if-no-files-found: ignore

      - name: IsBin
        if: steps.check_bin.outputs.files_exists == 'true'
        run: echo [SUCCESS] The binary file was succesfuly created !

      - name: CatCov
        if: steps.check_files.outputs.files_exists == 'true'
        run: cat test_coverage.txt

      - name: cleanup
        run: make fclean