name: unit-test
on: [push]
jobs:

  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello World !

  tests:
    runs-on: ubuntu-latest
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: dev

      - name: unit-test
        run: make tests_run

      - name: coverage
        run: make coverage